update probes and add securityContext settings to address warnings
openshift/aws-vpce-operator pull request #56
Opened 2022-09-06 20:51 UTC by tonytheleg

Addresses [OSD-12964](https://issues.redhat.com/browse/OSD-12964)
- updates the readiness and liveness probes to check that the AWS auth secrets exist otherwise it cannot create a VPC Endpoint, this should fail the pod before it tries to reconcile a CR.
- since the type of creds required varies on STS or not, the check looks for both and passes as long as one of them is successful.
- Adds security context configuration that explicity sets what appears to be defaults. This is to address warnings I saw on deploying to a 4.11 cluster.

```shell
W0906 15:50:34.753365   64831 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "aws-vpce-operator" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "aws-vpce-operator" must set securityContext.capabilities.drop=["ALL"]), seccompProfile (pod or container "aws-vpce-operator" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
deployment.apps/aws-vpce-operator created
```

2022-09-06 20:56 UTC, mjlshen commented
Looks good! We should also remove this code as a result of this change https://github.com/openshift/aws-vpce-operator/blob/main/main.go#L104-L111

2022-09-07 00:09 UTC, mjlshen requested changes
Looks good! We should also remove this code as a result of this change https://github.com/openshift/aws-vpce-operator/blob/main/main.go#L104-L111

2022-09-07 12:26 UTC, tonytheleg commented
> Looks good! We should also remove this code as a result of this change https://github.com/openshift/aws-vpce-operator/blob/main/main.go#L104-L111

Yep, that makes sense to me. Changes pushed, thanks!

2022-09-07 12:52 UTC, mjlshen commented
/lgtm
/approve

2022-09-07 13:16 UTC, merged